from src.configurations import GraphConfiguration
from src.models.enums import StageType
from src.patterns.builder.pipeline import Pipeline
from src.patterns.builder.stage import PipelineStage
from src.patterns.builder.step import PipelineStep


def requires_ingestor():
    return (
        Pipeline(name='requires-ingestor')
        .add_stage(
            PipelineStage(
                name='load-data',
                stage_type=StageType.LOAD
            )
            .add_step(
                PipelineStep(
                    name='load-requires-data',
                    function=PipelineStep.read_data,
                    configuration=GraphConfiguration.REQUIRES
                )
            )
        )
        .add_stage(
            PipelineStage(
                name='rename-data',
                stage_type=StageType.RENAME
            )
            .add_step(
                PipelineStep(
                    name='rename-requires-columns',
                    function=PipelineStep.rename,
                    column_mapping=GraphConfiguration.REQUIRES.column_mapping
                )
            )
        )
        .add_stage(
            PipelineStage(
                name='cast-data',
                stage_type=StageType.CAST
            )
            .add_step(
                PipelineStep(
                    name='cast-uuid-column-to-string',
                    function=PipelineStep.cast,
                    column='uid',
                    data_type=str
                )
            )
            .add_step(
                PipelineStep(
                    name='cast-course-id-column-to-string',
                    function=PipelineStep.cast,
                    column='course_id',
                    data_type=str
                )
            )
            .add_step(
                PipelineStep(
                    name='cast-requisite-id-column-to-string',
                    function=PipelineStep.cast,
                    column='requisite_id',
                    data_type=str
                )
            )
        )
        .add_stage(
            PipelineStage(
                name='partition-data',
                stage_type=StageType.PARTITION
            )
            .add_step(
                PipelineStep(
                    name='generate-partition-id',
                    function=PipelineStep.generate_partition_uid,
                    configuration=GraphConfiguration.REQUIRES
                )
            )
            .add_step(
                PipelineStep(
                    name='partition-requires-data',
                    function=PipelineStep.partition,
                )
            )
        )
        .add_stage(
            PipelineStage(
                name='ingest-data',
                stage_type=StageType.INGEST
            )
            .add_step(
                PipelineStep(
                    name='ingest-requires-data',
                    function=PipelineStep.ingest_relationships,
                    configuration=GraphConfiguration.REQUIRES
                )
            )
        )
    )
